spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/goldentime
#    username: root
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goldentime?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 14godhsl@@

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
